bot:
  name: IndependentBot
  token: 5684553448:AAHV4Alv_F3GKj_2LpIXhGx6LNLQYuZUGSc

spring:
  main:
    allow-circular-references: true

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure=ERROR: